name: Artifact

on: [push]

env:
  ARTIFACT_NAME: my-artifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code 
        uses: action/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
  
